# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Complexe
                                 A QGIS plugin
 Assistant complexe
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import Qt
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Import the code for the dialog
from .topo_sem_dialog import TopoSemDialog
from .constantes import *

class TopoSem:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.dlg = None
        self.iface = iface

    def initGui(self):
        pass
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

    def unload(self):
        pass

    def run(self):
        if self.dlg is not None and self.dlg.isVisible():
            return

        self.dlg = TopoSemDialog()

        # show the dialog
        self.dlg = TopoSemDialog()
        self.dlg.setParent(self.iface.mainWindow())
        self.dlg.setWindowFlags(Qt.Dialog | Qt.WindowTitleHint | Qt.WindowCloseButtonHint)
        self.dlg.setWindowTitle(TITRE)
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
